2025-08-09 10:56:05,682 - app - ERROR - [b863e548-b74d-4a87-8bcb-11435a1f2d5b] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 10:56:41,850 - app - ERROR - [42375dea-e21e-40e4-9502-ff3ecf170bf5] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 11:10:51,520 - app - ERROR - [3f6a069f-2c12-4118-9024-20c218453cc5] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 11:11:51,431 - app - ERROR - [96a2f4d4-696d-4532-a3a7-a9dd578fab57] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 11:12:08,391 - app - ERROR - [ef7e847d-a87e-4e0f-a3a8-9c0b247e26b5] Unhandled exception: Could not build url for endpoint 'base.dashboard'. Did you mean 'base.index' instead?
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/app/views/auth.py", line 160, in login
    return redirect(url_for('base.dashboard'))
                    ~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 232, in url_for
    return current_app.url_for(
           ~~~~~~~~~~~~~~~~~~~^
        endpoint,
        ^^^^^^^^^
    ...<4 lines>...
        **values,
        ^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'base.dashboard'. Did you mean 'base.index' instead?
2025-08-09 11:23:10,898 - app - ERROR - [c0421b9c-b0f8-4b8a-bb8e-0c07de36fb58] Unhandled exception: Could not build url for endpoint 'base.dashboard'. Did you mean 'base.user' instead?
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/app/views/base.py", line 29, in admin
    return render_template('admin/dashboard.html',
                           title='Dashboard',
                           DASHBOARD=True)
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/thunder/Projects/moneytracker/app/templates/admin/dashboard.html", line 1, in top-level template code
    {% extends "shared/adminlayout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/app/templates/shared/adminlayout.html", line 25, in top-level template code
    <a class="nav-link {% if DASHBOARD %}active{% endif %}" href="{{ url_for ('base.dashboard') }}">
    ^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'base.dashboard'. Did you mean 'base.user' instead?
2025-08-09 11:25:33,353 - app - ERROR - [3b018150-57ef-40af-847d-3468e1a9d792] Unhandled exception: Could not build url for endpoint 'base.dashboard'. Did you mean 'base.user' instead?
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/app/views/base.py", line 29, in admin
    return render_template('admin/dashboard.html',
                           title='Dashboard',
                           DASHBOARD=True)
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/thunder/Projects/moneytracker/app/templates/admin/dashboard.html", line 1, in top-level template code
    {% extends "shared/adminlayout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/app/templates/shared/adminlayout.html", line 25, in top-level template code
    <a class="nav-link {% if DASHBOARD %}active{% endif %}" href="{{ url_for ('base.dashboard') }}">
    ^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
        endpoint,
    ...<3 lines>...
        force_external=_external,
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'base.dashboard'. Did you mean 'base.user' instead?
2025-08-09 11:28:34,187 - app - ERROR - [d56ac1d7-e7e5-4910-b48c-c142a55bb88a] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 11:35:31,816 - app - ERROR - [a306b28b-cba3-4f09-a608-6e478f1fdfea] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 11:35:45,406 - app - ERROR - [06140339-0da0-462f-b39a-aebf98ba02db] Unhandled exception: shared/userlayout.html
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/app/views/base.py", line 19, in user
    return render_template('user/dashboard.html',
                           title='Dashboard',
                           DASHBOARD=True)
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/thunder/Projects/moneytracker/app/templates/user/dashboard.html", line 1, in top-level template code
    {% extends "shared/userlayout.html" %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/templating.py", line 65, in get_source
    return self._get_source_fast(environment, template)
           ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/templating.py", line 99, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: shared/userlayout.html
2025-08-09 11:36:11,968 - app - ERROR - [9add0315-37cb-45d1-a4d2-23604ba2e701] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 11:36:29,078 - app - ERROR - [d99f48e8-0695-40b7-9296-5aa034bd1c5f] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 11:38:36,294 - app - ERROR - [82c6a086-c32e-402f-bb1f-6f5ab9bbb86e] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 11:38:52,354 - app - ERROR - [c5e01ed6-bcb4-49bf-95ec-77b60ef36f54] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 11:39:27,520 - app - ERROR - [633708e2-29ef-4c3b-a996-196c76ed8f8c] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 11:40:01,368 - app - ERROR - [42039966-6e1c-434e-8df8-f2bd379db999] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
2025-08-09 11:40:28,361 - app - ERROR - [ad4f4e61-d726-4f89-ab07-09f18fe1998d] Unhandled exception: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
Traceback (most recent call last):
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 278, in <lambda>
    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950
                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/app.py", line 326, in send_static_file
    return send_from_directory(
        t.cast(str, self.static_folder), filename, max_age=max_age
    )
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/flask/helpers.py", line 565, in send_from_directory
    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        directory, path, **_prepare_send_file_kwargs(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/thunder/Projects/moneytracker/env/lib/python3.13/site-packages/werkzeug/utils.py", line 575, in send_from_directory
    raise NotFound()
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
